<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="pc" failures="0" tests="2" name="com.jobapplication.PersonalInfoTests" time="0.130" errors="1" timestamp="20 Tem 2018 17:23:34 GMT" skipped="1">
  <testcase classname="com.jobapplication.PersonalInfoTests" name="setUp" time="0.130">
    <error message="org/apache/commons/lang3/SystemUtils" type="java.lang.NoClassDefFoundError">
      <![CDATA[java.lang.NoClassDefFoundError: org/apache/commons/lang3/SystemUtils
at io.github.bonigarcia.wdm.Config.defaultOsName(Config.java:170)
at io.github.bonigarcia.wdm.Config.<init>(Config.java:73)
at io.github.bonigarcia.wdm.WebDriverManager.config(WebDriverManager.java:113)
at io.github.bonigarcia.wdm.WebDriverManager.<init>(WebDriverManager.java:93)
at io.github.bonigarcia.wdm.ChromeDriverManager.<init>(ChromeDriverManager.java:38)
at io.github.bonigarcia.wdm.WebDriverManager.chromedriver(WebDriverManager.java:120)
at com.jobapplication.PersonalInfoTests.setUp(PersonalInfoTests.java:21)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:458)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:168)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:105)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.lang3.SystemUtils
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
... 33 more
]]>
    </error>
  </testcase> <!-- setUp -->
  <testcase classname="com.jobapplication.PersonalInfoTests" name="fullNameEmptyTest" time="0.000">
    <skipped/>
  </testcase> <!-- fullNameEmptyTest -->
</testsuite> <!-- com.jobapplication.PersonalInfoTests -->
